name: rename_app_plus
description: A flutter package to rename app.
version: 1.2.1
homepage: "https://github.com/anvu69/rename_app_plus"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: any

dev_dependencies:
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
